ealias c='curl'
ealias d='docker'
ealias di='docker images'
ealias ds='docker service'
ealias dsi='docker service inspect'
ealias dslogs='docker service logs -f --tail=100'
ealias dslogss='docker service logs -f --tail=100'
ealias dslogsss=docker service logs -f --tail=100
ealias dsp='docker service ps'
ealias gc='git clone'
ealias gco='git checkout'
ealias h='history | grep'
